Implement backpack.fetch console command
LaserHydra/Backpacks pull request #6
Opened 2020-06-19 01:55 UTC by WheteThunger

Allow players to move specific items from their backpack to their inventory
with a console command.

2020-06-28 14:30 UTC, LaserHydra commented
Thank you for your contribution.

I am not opposed to adding the backpack.fetch command, however I feel like it maybe doesn't quite fit how the plugin is supposed to be used. Even then, it'd probably be an advanced feature not many people make use of, which would provide an advantage to certain players.
As a compromise, I am okay with this as long as it can be enabled/disabled in the config file. Maybe even default to disabled.

Since the backpack.fetch command does do some of the same checks as when opening a backpack, please create one "CanOpenBackpack" method which can then be used by both the command and when opening a backpack the usual way so we don't repeat ourselves.

Finally, please move any spacing/formatting changes to a separate PR (maybe together with the variable rename from https://github.com/LaserHydra/Backpacks/pull/7), or at least a separate commit.

2020-06-28 22:27 UTC, WheteThunger commented
- I added a separate `backpacks.fetch` permission instead of a config option so it can be separately granted since it can provide an advantage for more savvy players
- I have undone the formatting changes that my IDE originally imposed

2020-07-11 20:12 UTC, WheteThunger commented
Based on some older threads on the Backpacks support forum, I thought it would be wise to test if this can leak entities. I did some testing and found no leaks.
- Successfully transferring a full stack did not increase entity count when repeated many times.
- Splitting a stack and successfully transferring it did not entity count when repeated many times.
- Splitting a stack, unsuccessfully transferring that stack to the inventory, and forgetting about the split stack did not increase entity count when repeated many times. Seems it gets garbage collected  and the game properly cleans it up.

2020-07-11 20:18 UTC, WheteThunger commented
Rebased and renamed `_CanOpenBackpack` -> `VerifyCanOpenBackpack`.

2020-08-02 12:59 UTC, LaserHydra requested changes
Good work, please just use `int.TryParse` where indicated and this should be good to go.

2020-08-02 12:59 UTC, LaserHydra commented on Backpacks.cs
> +                    itemID = Int32.Parse(itemArg);
Please use `int.TryParse` here.

2020-08-02 12:59 UTC, LaserHydra commented on Backpacks.cs
> +                desiredAmount = Int32.Parse(args[1]);
Please use `int.TryParse` here too.

2020-08-07 11:49 UTC, LaserHydra commented
Good work, thanks again!

2020-08-07 11:50 UTC, merged